Fix Issue #201
andygrunwald/FOM-LaTeX-Template pull request #203
Opened 2021-02-17 15:51 UTC by SimonHaak

Das Paket, dass mit #188 eingebaut wurde und dafür gesorgt hat, dass die Nummer der Fußnote auf die Fußnote verlinkt wurde aktualisiert und enthält den genutzten Befehl nicht mehr. Das führt zum in #201 beschriebenen Fehler wenn die aktuelle Paketversion verwendet wird.

Um das Dokument wieder kompilieren zu können habe ich den commit [2d2950c](https://github.com/andygrunwald/FOM-LaTeX-Template/pull/188/commits/2d2950cf886b8fcbf00054c45be4f25df39f0c5c) wieder ausgebaut.

2021-02-17 16:38 UTC, andygrunwald requested changes
Sieht sehr gut aus.
Hab nur ein paar kleine Änderungen im GitHub Actions workflow.

2021-02-17 16:38 UTC, andygrunwald commented on .github/workflows/actions.yml
> +            ./compile.sh
What do you think about splitting the compile steps into two separate compile steps?
This would help to get the logs split.

```suggestion
      - name: Compile LaTeX document (German)
        uses: xu-cheng/latex-action@v2
        with:
          run: |
            ./compile.sh
      - name: Compile LaTeX document (English)
        uses: xu-cheng/latex-action@v2
        with:
          run: |
            ./compile.sh en
```

2021-02-17 16:38 UTC, andygrunwald commented on .github/workflows/actions.yml
> +      - main
Here, I suggest to trigger for every push.
Why? If we push new code to a branch, a build is triggered. The person is getting quick feedback.
Even if the person opens a PR, the build status is reported.

Additionally, we compile it every night. Why? To check for early regressions in 3rd party packages.
```suggestion
  push:
  schedule:
    - cron: "5 1 * * *"
```

2021-02-17 16:50 UTC, SimonHaak commented
Nachdem ich den Merge gemacht habe ist mir vorhin noch eine Idee gekommen:
Bisher bauen wir noch darauf, dass bei Änderungen die geänderten PDF Dateien hochgeladen werden. Das wird aber immer mal wieder vergessen und dann spiegelt die .pdf nicht mehr die aktuelle Version wieder.
Mit Github Actions haben wir ja aber auch die Möglichkeit Releases zu verwenden und dort die richtigen PDF Dateien aus der Action hochzuladen. Da sollten wir nochmal drüber nachdenken bevor wir die Änderung übernehmen.

Vorschlag wäre zwei Actions zu implementieren: 

1. triggert beim Pull Request und lädt die PDF Dateien als Artifact hoch. Die könnte auch wie von dir, Andy, vorgeschlagen jede Nacht laufen
2. triggert nur beim Push in den master und erstellt direkt einen neues Release. (Aus dem Repo selbst sollten wir die PDF Dateien dann entfernen)


Was haltet ihr davon?

2021-02-17 17:58 UTC, andygrunwald commented
@SimonHaak finde ich sehr gut, die Idee. Ich würde das jedoch Stück für Stück machen.
Erst den Change hier mergen und in einem neuen PR das Artifact erzeugen.

Zum Workflow würde ich wie folgt vorschlagen (aufbauend auf deinen Ideen):

1. triggert beim Pull Request und lädt die PDF Dateien als Artifact ZUM PR hoch. Somit können wir innerhalb eines PRs immer verifizieren, dass das PDR auch gut ist
2. triggert nur beim Push in den master und erstellt direkt einen neues Release. (Aus dem Repo selbst sollten wir die PDF Dateien dann entfernen)
3. Pipeline, die wir Nachts laufen lassen, soll nur compilen. Hier sehe ich keine Notwendigkeit ein PDF irgendwo hochzuladen. Da gilt es nur, zu verifizieren, dass alles noch funktioniert (zB wäre uns der Change in #201 früher aufgefallen)

Was sagst dazu?

2021-02-17 18:07 UTC, SimonHaak commented
Jetzt ist hier schon so viel Aktivität im Repo, dass wir uns gegenseitig überholen. Auch mal schön :)
Genau die Vorschläge wie du sie formuliert hast habe ich schon umgesetzt.

Eigentlich wollte ich die beiden Changes auch gar nicht durcheinanderwerfen. Das ist mir beim testen passiert, weil ich ja verifizieren musste, dass meine Änderungen hier die ich für #201 gemacht habe auch funktionieren.

Vorschlag:
Ich entferne die actions.yml  aus dem Branch. Dann kann der Pull Request hier gemerged werden und das Template lässt sich schon mal von allen wieder kompilieren. Alles zu Github Actions können wir dann im Nachhinein klären.
Okay?

2021-02-18 12:56 UTC, andygrunwald commented
Passt! Danke @SimonHaak

2021-02-19 07:37 UTC, andygrunwald approved these changes

2021-02-19 07:37 UTC, merged