GitHub actions CI
andygrunwald/FOM-LaTeX-Template pull request #205
Opened 2021-02-19 10:56 UTC by SimonHaak

Hallo zusammen,
wie in #198 diskutiert hier ein Vorschlag für den Umbau von Travis CI zu github Actions.
Die Action ist dreigeteilt:

1. Jede Nacht wird einmal kompiliert um Sicherzustellen, dass es mit allen Abhängigkeiten noch funktioniert (siehe #201)
2. Bei jedem push in das repo wird kompiliert und das Ergebnis als Artifact hochgeladen, damit die PDF Dateien evaluiert werden können
3. Pei einem push in den Master wird kompiliert und ein neues draft release angelegt

Schaut euch den Code gerne genauer an, Github Actions sind mir bisher neu.

2021-02-19 12:27 UTC, andygrunwald requested changes
Smaller changes suggested.
Otherwise, good to go!

2021-02-19 12:27 UTC, andygrunwald commented on README.md
> +[![Build](https://github.com/SimonHaak/FOM-LaTeX-Template/actions/workflows/Check.yml/badge.svg)](https://github.com/SimonHaak/FOM-LaTeX-Template/actions/workflows/Check.yml)
```suggestion
[![Build](https://github.com/andygrunwald/FOM-LaTeX-Template/actions/workflows/Check.yml/badge.svg)](https://github.com/andygrunwald/FOM-LaTeX-Template/actions/workflows/Check.yml)
```

Just a small change to make it work after being merged.

2021-02-19 12:27 UTC, andygrunwald commented on .github/workflows/Check.yml
> +  workflow_dispatch:
Quick question: Do we need to run this workflow manually? (that is my understanding from reading https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).

In my experience, we should make it work without manual intervention. What do you think?

2021-02-19 12:27 UTC, andygrunwald commented on .github/workflows/Check.yml
> +        if: github.event_name == 'push'
```suggestion
        if: github.ref != 'refs/heads/master' &&  github.event_name == 'push'
```
Not sure what the best way is to determine if the push happens in a PR, but adding the `ref` check here, avoids creating artifacts in master (because we create it on release).

2021-02-19 12:27 UTC, andygrunwald commented on .github/workflows/Check.yml
> +        if: github.event_name == 'push'
```suggestion
        if: github.ref != 'refs/heads/master' &&  github.event_name == 'push'
```
See below.

2021-02-19 12:27 UTC, andygrunwald commented
Wenn dies gemerged ist, deaktiviere ich TravisCI komplett.

2021-02-19 17:16 UTC, SimonHaak commented on .github/workflows/Check.yml
> +  workflow_dispatch:
No, we do not NEED to run this workflow manually. I just wanted to have the possibility just in case. I can remove it if you like.

2021-02-19 17:17 UTC, SimonHaak commented on .github/workflows/Check.yml
> +        if: github.event_name == 'push'
That's a good Idea. Having the artifacts created would not be a real issue, but you are right, we don't need them for pull requests.

2021-02-20 07:58 UTC, andygrunwald commented on .github/workflows/Check.yml
> +  workflow_dispatch:
Lets keep it as is :)

2021-02-20 07:58 UTC, merged